### ISSUE TITLE
Torch not complied with CUDA enabled error

### ISSUE THREAD

**Issue by waltmannz** [olegchomp/TouchDiffusion#10]
After following the instructions using the portable archive and opening the tox I get this error message inside of touchdesigner

AssertionError: Torch not complied with CUDA enabled (/project1/TouchDiffusion)

**Comment by olegchomp** [comment]
Better to provide full log (ALT + T in TD). Also check if TD version is 2023

**Comment by eisenbruch** [comment]
I am having this issue too. Here is my log:

TouchDesigner  Build 2023.12120 compile on Mon Dec 16 15:05:18 2024
Python 3.11.1 (heads/3.11-Derivative-dirty:82b0389147, Jan 25 2023, 22:34:27) [MSC v.1929 64 bit (AMD64)]

Warning: '.venv/Lib/site-packages' is not a valid directory.
Warning: 'embedded_python/Lib/site-packages' is not a valid directory.
Warning: 'StreamDiffusion/src' is not a valid directory.
Warning: '' is not a valid directory.
Error retrieving extension for /project1/TouchDiffusion: (Extension 1)   File "/project1/TouchDiffusion/TouchDiffusionExt", line 29, in __init__
  File "C:\Users/spinn/AppData/Local/Programs/Python/Python311/Lib/site-packages\torch\cuda\__init__.py", line 979, in current_stream
    _lazy_init()
  File "C:\Users/spinn/AppData/Local/Programs/Python/Python311/Lib/site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "/project1/TouchDiffusion/parexec1", line 9, in onValueChange
AttributeError: 'NoneType' object has no attribute 'parexec_onValueChange'
Added 'Tools/TouchDiffusion-main\.venv/Lib/site-packages' to sys.path.
Warning: 'Tools/TouchDiffusion-main\embedded_python/Lib/site-packages' is not a valid directory.
Added 'Tools/TouchDiffusion-main\StreamDiffusion/src' to sys.path.
Added 'Tools/TouchDiffusion-main' to sys.path.
Error retrieving extension for /project1/TouchDiffusion: (Extension 1)   File "/project1/TouchDiffusion/TouchDiffusionExt", line 29, in __init__
  File "C:\Users/spinn/AppData/Local/Programs/Python/Python311/Lib/site-packages\torch\cuda\__init__.py", line 979, in current_stream
    _lazy_init()
  File "C:\Users/spinn/AppData/Local/Programs/Python/Python311/Lib/site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
  File "/project1/TouchDiffusion/parexec1"
Error retrieving extension for /project1/TouchDiffusion: (Extension 1)   File "/project1/TouchDiffusion/TouchDiffusionExt", line 29, in __init__
  File "C:\Users/spinn/AppData/Local/Programs/Python/Python311/Lib/site-packages\torch\cuda\__init__.py", line 979, in current_stream
    _lazy_init()
  File "C:\Users/spinn/AppData/Local/Programs/Python/Python311/Lib/site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
  File "/project1/TouchDiffusion/script1"
Traceback (most recent call last):
  File "/project1/TouchDiffusion/parexec1", line 28, in onPulse
AttributeError: 'NoneType' object has no attribute 'parexec_onPulse'
