### ISSUE TITLE
No errors during installation, error on component

### ISSUE THREAD

**Issue by function-store** [olegchomp/TouchDiffusion#5]
I was following the install steps according to the yt video, and have not gotten any errors. In TD I get the following though:

![image](https://github.com/olegchomp/TouchDiffusion/assets/47873029/7d9f04eb-09dd-43d9-b9cf-5a195b8c9ae2)

**Comment by olegchomp** [comment]
What's in 
nvcc --version

Did you get pop up error?

**Comment by function-store** [comment]
```nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0```

I got some errors pop up when trying to translate the model, but that was fixed. Other than that no errors in cmd.

**Comment by olegchomp** [comment]
Fixed with "fix pop up window" button or manually?

**Comment by function-store** [comment]
20223.11760

Python version is 3.11, the one used in the youtube tutorial. I followed all those steps.

**Comment by function-store** [comment]
I fixed using the button.

**Comment by olegchomp** [comment]
And you can create engine in webui?

**Comment by function-store** [comment]
yep, no errors there, and `status: ready`

**Comment by olegchomp** [comment]
Maybe you have integrated GPU?

**Comment by olegchomp** [comment]
You might try with 2023.11340 as version I tested. But all solution I found are about reinstalling torch. You can make it manually. 


```
.venv\Scripts\activate.bat
pip install torch==2.1.0 torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cu118

```

**Comment by function-store** [comment]
tried that and also to force the reinstall. Also redid all the steps and still the same issue :(

**Comment by olegchomp** [comment]
Can you install torch in Python 3.11 without venv?

**Comment by alilia** [comment]
I'd like to reinitiate that issue. Same error here. Here is the Textport output. Since all suggestions are about reinstalling Torch which has no impact on that error, I will try applying what the output suggests.

## Versions

Since it was asked earlier:

* TD version: 2023.11880
* Python version: 3.10.0
* `nvcc --version`:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

## Troubleshooting

* can create engine in webui: yes
* popup error fixed using the button: yes

## Whole error

(updated username to `USERNAME`):

```
Warning: 'TouchDiffusion\embedded_python/Lib/site-packages' is not a valid directory.
DAT compile error: /project_template/TouchDiffusion/TouchDiffusionExt
Traceback (most recent call last):
  File "/project_template/TouchDiffusion/TouchDiffusionExt", line 4
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\Documents\Stable Diffusion\TouchDiffusion\.venv/Lib/site-packages\torch\__init__.py", line 451
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

Error retrieving extension for /project_template/TouchDiffusion: (Extension 1) td.tdError: Module compilation error. See /project_template/TouchDiffusion/TouchDiffusionExt for details.
  File "/project_template/TouchDiffusion/parexec1"
DAT compile error: /project_template/TouchDiffusion/TouchDiffusionExt
Traceback (most recent call last):
  File "/project_template/TouchDiffusion/TouchDiffusionExt", line 4
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\Documents\Stable Diffusion\TouchDiffusion\.venv/Lib/site-packages\torch\__init__.py", line 451
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
DAT compile error: /project_template/TouchDiffusion/TouchDiffusionExt
Traceback (most recent call last):
  File "/project_template/TouchDiffusion/TouchDiffusionExt", line 4
    r = previousimport(*args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\Documents\Stable Diffusion\TouchDiffusion\.venv/Lib/site-packages\torch\__init__.py", line 451
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

Error retrieving extension for /project_template/TouchDiffusion: (Extension 1) td.tdError: Module compilation error. See /project_template/TouchDiffusion/TouchDiffusionExt for details.
  File "/project_template/TouchDiffusion/script1"
```

**Comment by olegchomp** [comment]
@alilia if it's manual installation, python should be 3.11

**Comment by alilia** [comment]
Sure, let me try. However, I was downgrading explicitly to 3.10 due to some Stable Diffusion installation. Will get back to you as soon as I check it (maybe only tmrw).

Also, if that is useful information: [TDDiffusionAPI](https://github.com/olegchomp/TDDiffusionAPI) works with the current setup.

**Comment by olegchomp** [comment]
@alilia there is difference in TD pipeline. 
TDDiffusionAPI & TDComfyUI works through API with environment. 
TouchDiffusion run code inside of TD and because of that depends on TD python version (2023 is 3.11, 2022 is 3.10) to build environment.  
There is Portable version to skip installation part, you might try it if still doesn't install correctly.

**Comment by alilia** [comment]
Thanks a bunch, mate!

Yes, installing a separate version of Python 3.11 solved the issue. The stream is happening in TD and I can continue playing around. (Now I also see the version being mentioned in the description as well.)

Also, that is me on my way to buy you a coffee:
![happy walking](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExbGxud3c4cG9hZzc1Zm53NTA1Y2dvY2N3dm82cjhtZ215enptNzJ4YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/rDDv72OIYB39K/200.webp)
