### ISSUE TITLE
Make engine error

### ISSUE THREAD

**Issue by donbeumai** [olegchomp/TouchDiffusion#7]
![image](https://github.com/olegchomp/TouchDiffusion/assets/145892779/7fad641c-f68f-46b0-bb75-8bedfd11e0cf)

![image](https://github.com/olegchomp/TouchDiffusion/assets/145892779/3018135e-7747-450d-a254-0c468cdbf5bf)

I get an error with make engine in web ui.
in this video.
https://youtu.be/3WqUrWfCX1A?t=265

**Comment by dystopiaat** [comment]
Got the same error, it seems that it can't find the model. I dowloaded the exact same model into "C:\TouchDiffusion-main\StreamDiffusion\models\checkpoints"


Git is installed.
Activating virtual environment...
Launching WebUI...
C:\TouchDiffusion-main\.venv\Lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
Directory already exists: models
Directory already exists: models/acceleration_loras
Directory already exists: models/checkpoints
Directory already exists: models/loras
Directory already exists: models/vae
Directory already exists: engines
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
dreamshaper_8
Model load has failed. Doesn't exist.
Invalid `pretrained_model_name_or_path` provided. Please set it to a valid URL.
Traceback (most recent call last):
  File "C:\TouchDiffusion-main\.venv\Lib\site-packages\gradio\queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\.venv\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\.venv\Lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\.venv\Lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\.venv\Lib\site-packages\gradio\utils.py", line 833, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\StreamDiffusion\webui.py", line 49, in stream_engine
    stream = StreamDiffusionWrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\StreamDiffusion\utils\wrapper.py", line 164, in __init__
    self.stream: StreamDiffusion = self._load_model(
                                   ^^^^^^^^^^^^^^^^^
  File "C:\TouchDiffusion-main\StreamDiffusion\utils\wrapper.py", line 480, in _load_model
    pipe=pipe,
         ^^^^
UnboundLocalError: cannot access local variable 'pipe' where it is not associated with a value

**Comment by carloslavina** [comment]
same over here. Can't get it to work, not sure of what all that text mean. Help :S

**Comment by Vontastic** [comment]
Same problem. Has anyone discovered a solution?

**Comment by olegchomp** [comment]
Update to latest version, this errors fixed.

**Comment by rubfabbri** [comment]
I'm still have the same problem, and I already update the dependencies.  Does anyone fixed this?

**Comment by olegchomp** [comment]
Download Portable version and follow steps in instruction, it have latest stable updates

**Comment by rubfabbri** [comment]
> rsion and follow steps in instruction, it have latest stable updates

I already download the portable version and do the update of dependence but still in portable version I had the same issue:

UnboundLocalError: cannot access local variable 'pipe' where it is not associated with a value.
